### ISSUE TITLE
Can't use directly as an ES module in the browser

### ISSUE THREAD

**Issue by davidbwaters** [johh/three-effectcomposer#7]
Hi, so apparently the way Babel transpiled this from source, it can't be used directly as an ES module without a bundler.  I found this out trying to use it with 'es-dev-server', which serves ES modules directly in the browser in development. The source code works. I raised an issue here https://github.com/open-wc/open-wc/issues/1798 but it looks like it's a transpilation issue.

**Comment by johh** [comment]
Hey, sorry for the late reply. You're correct, right now only the cjs version is shipped. The `/src` directory was supposed to be included in the npm package to provide native ES modules, but I managed to exclude it somewhere along the way.
I'll provide a native, bundled ES version ASAP and publish an update.

**Comment by johh** [comment]
After looking into it: Since v105, `three` [includes ES module versions](https://github.com/mrdoob/three.js/blob/master/examples/jsm/postprocessing/EffectComposer.js) of everything postprocessing related in the npm package. You should be able to import them from `three/examples/jsm/postprocessing/EffectComposer.js`, etc.

I'll still push the update but will deprecate `@johh/three-effectcomposer` as it is now redundant.

**Comment by johh** [comment]
I've updated the package and added a deprecation notice.
